version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Stub testing"
          command: echo "This is an stub. Replace with valid step."